Reassign ownership of the dbdir on start up
WildMeOrg/wildbook-ia pull request #184
Opened 2021-02-09 03:39 UTC by mmulich

This ensures container's runtime user has access to read and write to
the database directory.

Ran into this usecase within compose when assigning a named volume.

```
services:
  wbia:
    image: wildme/wildbook-ia:latest
    ...
    volumes:
      - wbia-var:/data/db
volumes:
  wbia-var:
```

2021-02-22 21:11 UTC, bluemellophone commented
I learn towards rejecting this PR because it makes some strong assumptions about the underlying data on the host machine.  For example, if the user ID is not mapped properly for user `wbia` inside the container, where outside it may be mangled and unassigned to an unknown user.  Further, it is not assumed that the group of the data should be the same as the user `wbia`, especially for multi-admin systems.

I would like to make the ownership of the data directory out of scope for running WBIA.  We can do a check, but doing a forced update (especially with `-R`) seems unnecessarily risky and maybe also cost time on start up.

2021-02-22 21:13 UTC, bluemellophone requested changes
This PR needs to be closed as data directory ownership (and permissions) are out of scope or should be updated to do a cursory write check in the data directory on start-up.

2021-02-23 23:26 UTC, bluemellophone commented
@mmulich poke

2021-02-24 20:09 UTC, closed without merging

2021-02-24 20:12 UTC, mmulich commented
I believe I've worked around the issue by mounting one directory lower as opposed to mounting the volume at the specific location.